# Handling Imbalanced Dataset
1. Upsampling
2. Downsampling

In [10]:
import numpy as np
import pandas as pd
np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0  = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [11]:
n_class_0, n_class_1

(900, 100)

In [12]:
# Create a dataframe with imbalanced data set
class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] * n_class_0

})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1] * n_class_1
    
})

In [13]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [14]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [15]:
df.tail()

     feature_1  feature_2  target
995  -0.623629   0.845701       1
996   0.239810  -1.119923       1
997  -0.868240  -0.359297       1
998   0.902006  -1.609695       1
999   0.697490   0.013570       1

In [16]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [17]:
# Upsampling 
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [18]:
from sklearn.utils import resample
upsampled = resample(df_minority,replace=True,n_samples=len(df_majority), random_state=42)

In [19]:
upsampled.shape

(900, 3)

In [20]:
df_minority.head()

     feature_1  feature_2  target
900  -0.300232   0.139033       1
901  -0.632261   0.025577       1
902  -0.204317  -0.196443       1
903   0.213696   1.312255       1
904   1.033878   1.187417       1

In [22]:
pd.concat([df_minority,upsampled]).reset_index()

     index  feature_1  feature_2  target
0      900  -0.300232   0.139033       1
1      901  -0.632261   0.025577       1
2      902  -0.204317  -0.196443       1
3      903   0.213696   1.312255       1
4      904   1.033878   1.187417       1
..     ...        ...        ...     ...
995    952  -0.811098   0.189189       1
996    965   1.919526  -0.019459       1
997    976   0.810326   1.604614       1
998    942   1.621531   0.168229       1
999    974  -0.839113   0.489203       1

[1000 rows x 4 columns]

In [23]:
# Downsampling
downsampled = resample(df_majority, replace=False, n_samples=len(df_minority), random_state=42)

In [ ]:

downsampled

     feature_1  feature_2  target
70    0.468439   1.720920       0
827   1.089165  -0.464899       0
231   0.753869  -0.969798       0
588   0.588686  -0.704720       0
39    0.283627   1.012868       0
..         ...        ...     ...
398  -0.168426   0.553775       0
76   -0.403366   0.081491       0
196  -0.269293   0.611238       0
631  -0.295829   0.671673       0
751  -0.553404   0.804438       0

[100 rows x 3 columns]

In [25]:
df_downsampled = pd.concat([df_minority,downsampled]).reset_index()

In [27]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64