In [1]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))

In [6]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [7]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [ ]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [15]:
# Read JSON data
json_data = [
    {
        "id": 1,
        "name": "Alice",
        "email": "alice@example.com",

    },
    {
        "id": 2,
        "name": "Bob",
        "email": "bob@example.com",
    
    },
    {
        "id": 3,
        "name": "Charlie",
        "email": "charlie@example.com",
     
    }
]
pd.json_normalize(json_data)

   id     name                email
0   1    Alice    alice@example.com
1   2      Bob      bob@example.com
2   3  Charlie  charlie@example.com

In [17]:
json_data = [
    {
        "id": 1,
        "name": "Alice",
        "email": "alice@example.com",
        "scores": {
            "math": 85,
            "science": 90
        }
    },
    {
        "id": 2,
        "name": "Bob",
        "email": "bob@example.com",
        "scores": {
            "math": 78,
            "science": 83
        }
    },
    {
        "id": 3,
        "name": "Charlie",
        "email": "charlie@example.com",
        "scores": {
            "math": 92,
            "science": 87
        }
    }

]

pd.json_normalize(json_data)

   id     name                email  scores.math  scores.science
0   1    Alice    alice@example.com           85              90
1   2      Bob      bob@example.com           78              83
2   3  Charlie  charlie@example.com           92              87

In [16]:
# Read simpler json data
json_data= [
    {"id": 1, "name": "Alice", "math": 85, "science": 90},
    {"id": 2, "name": "Bob", "math": 78, "science": 83},
    {"id": 3, "name": "Charlie", "math": 92, "science": 87}    
    ]
pd.json_normalize(json_data)

   id     name  math  science
0   1    Alice    85       90
1   2      Bob    78       83
2   3  Charlie    92       87

In [22]:
url = 'https://fdic.gov/bank-failures/failed-bank-list'
df = pd.read_html(url)

In [23]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
1,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,"First Bank & Trust Co., Duncan, OK","October 18, 2024",10547
2,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
3,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
4,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
5,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
6,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
7,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
8,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
9,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537

In [26]:
url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
df = pd.read_html(url,match='Country')

In [28]:
df[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [37]:
sample = pd.ExcelFile(r"C:\Users\battih\Desktop\Exit_Path_Summary.xlsx")

In [39]:
sample.sheet_names

['Summary', 'Unapplied Data', 'FIFO Details']

In [40]:
df.parse(str('Summary'))

AttributeError: 'list' object has no attribute 'parse'

In [42]:
sample.parse(str('Summary'))

,Issuer,Obfuscated Customer Id,180+,Unapplied 91-180,Unapplied 61-90,Unapplied 31-60,Unapplied below 30,Bad Debt,90+ PD,30+ PD,Below 90 PD,Current AR,w/o invoices,Unapplied 365+,PD 180+,Tier,status
0,CA,A0865725UACUQLU2MO9P,-2124.08,-26.94,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,NaN,No AR
1,UK,A0865725UACUQLU2MO9P,-2124.08,-26.94,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,NaN,No AR
2,CA,A10H68YZAS7ML1,-305.40,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,NaN,No AR
3,CA,A111BC4EQFOXQ7,-605.48,-120.23,-251.96,0.0,0.0,0.0,5030.74,6352.84,2349.70,1416.56,5.98,0.0,3712.87,CAM,Unallocated
4,CA,A117UVD4AUCQS2,-57.96,0.00,0.00,0.0,0.0,0.0,0.00,0.00,92.59,3438.95,169.37,0.0,0.00,NaN,Unallocated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190326,UK,AZXMFIX0YOOXL,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,351.01,0.00,0.0,0.00,NaN,Current AR
190327,UK,AZY1P0ROZP6XV,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,110.26,0.00,0.0,0.00,NaN,Current AR
190328,UK,AZYU15SURW3OG,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,405.15,0.00,0.0,0.00,NaN,Current AR
190329,UK,AZYZMN1Z664KN,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,124.35,0.00,0.0,0.00,NaN,Current AR
190330,UK,AZZF9Z9785RMB,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,316.61,0.00,0.0,0.00,NaN,Current AR