# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [ ]:
import pandas as pd 
import numpy as np 

col = ['A','B','C','D']
data = np.random.randint(1,6,size=(6,4))
pd.DataFrame(data=data,columns=col)

   1  2  3  4
0  3  4  5  5
1  1  3  2  5
2  4  4  1  3
3  2  5  2  1
4  1  2  5  5
5  4  5  1  4

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [5]:
col = ['A','B','C','D']
idx = ['X','Y','Z']
data = np.random.randint(1,6,size=(3,4))
pd.DataFrame(data,columns=col,index=idx)

   A  B  C  D
X  3  3  4  5
Y  4  1  4  4
Z  3  5  1  4

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [8]:
col = ['X','Y','Z']
data = np.random.randint(1,100,size=(5,3))
df = pd.DataFrame(data,columns=col)
df['Product'] = df['X'] * df['Y']
df

    X   Y   Z  Product
0  18   7  22      126
1  43  40  96     1720
2  43  51  70     2193
3  69  15  50     1035
4  30   5  65      150

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [9]:
col = ['X','Y','Z']
data = np.random.randint(1,10,size=(4,3))
df = pd.DataFrame(data,columns=col)

row_sum = df.sum(axis=0)
col_sum = df.sum(axis=1)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(col_sum)

Row-wise sum:
X    13
Y    22
Z    16
dtype: int64
Column-wise sum:
0    11
1    17
2    16
3     7
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [27]:
col = ['X','Y','Z']
data = np.random.randint(1,10,size=(5,3))
df = pd.DataFrame(data,columns=col)
df.loc[0,['X']] = np.nan
df.loc[1,['Y']] = np.nan
df.loc[2,['Z']] = np.nan
print(df.head())
df.fillna(df.mean(),inplace=True)
df.head()

     X    Y    Z
0  NaN  8.0  9.0
1  3.0  NaN  2.0
2  2.0  2.0  NaN
3  6.0  7.0  2.0
4  1.0  6.0  2.0

     X     Y     Z
0  3.0  8.00  9.00
1  3.0  5.75  2.00
2  2.0  2.00  3.75
3  6.0  7.00  2.00
4  1.0  6.00  2.00

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [30]:
col = ['X','Y','Z']
data = np.random.randint(1,10,size=(5,3))
df = pd.DataFrame(data,columns=col)
df.loc[0,['X']] = np.nan
df.loc[1,['Y']] = np.nan
df.loc[2,['Z']] = np.nan
print(df.head())
df.dropna(axis=0,inplace=True)
df.head()

     X    Y    Z
0  NaN  8.0  6.0
1  7.0  NaN  3.0
2  1.0  7.0  NaN
3  7.0  2.0  7.0
4  5.0  3.0  7.0

     X    Y    Z
3  7.0  2.0  7.0
4  5.0  3.0  7.0

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [40]:
data = {
    'Category':np.random.choice(['A','B','C'],size=10),
    'Values':np.random.randint(1,100,size=10)
    }
df = pd.DataFrame(data)
df.groupby('Category')['Values'].agg(['sum','mean'])

          sum       mean
Category
A         357  59.500000
B         157  52.333333
C          52  52.000000

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [43]:
data = {
    'Product': np.random.choice(['A','B','C'],size=100),
    'Category': np.random.choice(['X','Y','Z'],size=100),
    'Sales': np.random.randint(1000,2000,size=100)
}
df = pd.DataFrame(data)
df.groupby(['Category'])['Sales'].sum().reset_index()

  Category  Sales
0        X  68373
1        Y  41304
2        Z  40905

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [45]:
df1 = pd.DataFrame(data={'column1':np.random.choice(['A','B','C','X','K'],size=20), 'Value1':np.random.randint(100,1000,size=20)})
df2 = pd.DataFrame(data={'column1':np.random.choice(['L','M','X','A','B'],size=20), 'Value2':np.random.randint(100,1000,size=20)})

pd.merge(df1,df2,how='inner',on='column1').head()

  column1  Value1  Value2
0       B     955     174
1       B     955     530
2       B     955     227
3       B     955     387
4       B     955     639

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [48]:
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

pd.concat([df1,df2],axis=1)

DataFrame 1:
    A   B
0  86  33
1  31  15
2  54  16
DataFrame 2:
    C   D
0  16  74
1  64  87
2  55  35

    A   B   C   D
0  86  33  16  74
1  31  15  64  87
2  54  16  55  35

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [62]:
date_range = pd.date_range('2025-01-01','2025-01-31',freq='D')
df = pd.DataFrame(np.random.randint(1,100,size=31),index=date_range,columns=['Value'])
df.index.name = 'Date'
df.head()
df.resample('M').mean()

C:\Users\battih\AppData\Local\Temp\ipykernel_41744\2000255215.py:5: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M').mean()

                Value
Date
2025-01-31  51.322581

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [67]:
date_range = pd.date_range(start='2021-01-01',end='2021-12-31')
df = pd.DataFrame(np.random.randint(100,900,size=365),index=date_range,columns=['Value'])
df.index.name = 'Date'
df.resample('7D').mean().head(20)

                 Value
Date
2021-01-01  678.857143
2021-01-08  468.000000
2021-01-15  619.142857
2021-01-22  477.571429
2021-01-29  619.000000
2021-02-05  491.571429
2021-02-12  540.428571
2021-02-19  550.714286
2021-02-26  526.285714
2021-03-05  381.571429
2021-03-12  313.857143
2021-03-19  564.857143
2021-03-26  340.000000
2021-04-02  523.857143
2021-04-09  427.857143
2021-04-16  570.142857
2021-04-23  421.142857
2021-04-30  316.428571
2021-05-07  479.285714
2021-05-14  401.714286

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.